### ISSUE TITLE
Failed relative require call

### ISSUE THREAD

**Issue by darsain** [makojs/js#70]
So, now I'm trying to build `index.js` of [xo](https://github.com/sindresorhus/xo) for a change :) and I get this:

```
Error: Cannot find module './options-manager' from 'D:\www\test\node_modules\mako-js'
    at D:\www\test\node_modules\resolve\lib\async.js:55:21
    at load (D:\www\test\node_modules\resolve\lib\async.js:69:43)
    at onex (D:\www\test\node_modules\resolve\lib\async.js:92:31)
    at D:\www\test\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)
```

The `./options-manager` is require call made at the top of said `index.js`, and is supposed to pick up the `./options-manager.js` located right next to it, but fails.

If it's any help, the build script looks like this:

```js
let filename = 'C:\\Users\\Darsain\\AppData\\Roaming\\npm\\node_modules\\xo\\index.js';
let root = path.dirname(filename);

let types = ['js', 'json', 'txt', 'exe', 'bat'];
let acornOptions = {allowReturnOutsideFunction: true};
let detectiveOptions = {parse: acornOptions};

del.sync(path.join(root, 'build'));

mako({root})
	.use(buffer(types))
	.use(js({browser: false, detectiveOptions}))
	.use(output(types, {dir: 'build'}))
	.use(write(types))
	.build(filename)
	.then(() => console.log('Done!'))
	.catch(console.error.bind(console));
```

**Comment by dominicbarnes** [comment]
That's really weird, I didn't expect the logic behind things like this to be changed in any way, but I'll take a look later today.
